version: '3.5'

services:
  project:
    container_name: lifehacker_test_project
    image: lifehacker_test_project
    build:
        context: .
        dockerfile: compose/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./logs:/logs
    command: /start
